chore(build): migrate to `pyproject.toml` for packaging
google-deepmind/dm_pix pull request #97
Opened 2024-04-09 12:57 UTC by SauravMaheshkar

Mirrors work done in:
* https://github.com/google-deepmind/optax/pull/513
* https://github.com/google-deepmind/optax/pull/737

`pyproject.toml` is the new standard for packaging python packages, `setup.py` is now deprecated (first introduced in [PEP 518](https://peps.python.org/pep-0518/) and later expanded in [PEP 517](https://peps.python.org/pep-0517/), [PEP 621](https://peps.python.org/pep-0621/) and [PEP 660](https://peps.python.org/pep-0660/)). This PR proposes to switch from the legacy `setup.py` method in favour of `pyproject.toml`. This would lead to a overall better project structure because all requirements would be managed within a single `pyproject.toml` file instead of 4 separate text files. It also allows for dynamic version allocation (reads automatically from `/__init__.py`). 

Changes proposed by this PR can be summarized as follows :-

* Delete `setup.py`  in favour of `pyproject.toml` for packaging and update the `test.sh` script appropriately.
* Update Github Actions Workflows with `cache` and `cache-dependency-path` and different build commands for uploading to pypi.
* Removing the now redundant `requirements*.txt` and `MANIFEST.in`.
* Updating "read the docs" configuration.

2024-04-09 13:26 UTC, claudiofantacci commented
Thanks for this PR! I'll try to have a look as soon as I can. In the meantime, can you have a look the CI that seems to be failing? Thanks again 🚀

2024-04-09 13:27 UTC, SauravMaheshkar commented
> Thanks for this PR! I'll try to have a look as soon as I can. In the meantime, can you have a look the CI that seems to be failing? Thanks again 🚀

Addressed in [495b8a8](https://github.com/google-deepmind/dm_pix/pull/97/commits/495b8a80624f4da429fb1777d5bbdc9e6099c606), it was a typo 😅

2024-04-09 13:32 UTC, claudiofantacci commented
Ok seems like that fixed it! 🚀 
I'll have a look asap, but skimming through it LGTM 👍

2024-04-12 17:28 UTC, SauravMaheshkar commented
Also maybe it's worth mentioning but with `optax` copybara was throwing some errors and then ultimately someone had to add a empty `pyproject.toml`. If that is the case I can rebase the PR with a single squash commit to make everything nice and clean.

2024-04-14 15:03 UTC, claudiofantacci commented
That's strange, in theory it should be a single squashed commit anyway.
In any case, given your prior with `optax` I would suggest doing that.
Can you please do it 😄 ?

2024-04-14 15:58 UTC, SauravMaheshkar commented
Happy to do it if necessary. Can you try running capybara on this PR?

Previously the GitHub CI had ran successfully however when attempting to merge, capybara was throwing an error. Can you try to run capybara on this PR? Incase there is an error I'll open another PR with an empty pyproject

2024-04-14 20:03 UTC, claudiofantacci reviewed
Thanks for the PR, only a few minor things before approving 😄

2024-04-14 20:03 UTC, claudiofantacci commented on test.sh
>  # Run setup.py, this installs the python dependencies
This is no longer what happens, can you please update the comment here?

2024-04-14 20:03 UTC, claudiofantacci commented on test.sh
>  # Install JAX.
This is also no longer the case, the same thing for line 22. Can you please update the comments to reflect the changed introduced by this PR?

2024-04-14 20:03 UTC, claudiofantacci commented on test.sh
> +	N_JOBS=$(sysctl -n hw.logicalcpu)
Please leave the two spaces.

2024-04-14 20:03 UTC, claudiofantacci commented on test.sh
> +	N_JOBS=$(grep -c ^processor /proc/cpuinfo)
Please leave the two spaces.

2024-04-18 09:54 UTC, SauravMaheshkar commented
I addressed the comments in the recent commits.

2024-04-18 10:28 UTC, claudiofantacci approved these changes
Thanks a lot, let's see what Copybara tells us ahah 😄

2024-04-18 11:04 UTC, claudiofantacci commented
I have a copybara failure, I'll look into it asap.

2024-04-22 08:06 UTC, SauravMaheshkar commented
> I have a copybara failure, I'll look into it asap.

Hey @claudiofantacci, I'm assuming this is because of a lack of `pyproject.toml` in the master branch atm. Can you make a PR via copybara which adds a empty `pyproject.toml` ? Then I can rebase my PR and we can try again.

2024-04-22 10:25 UTC, claudiofantacci commented
My Copybara is probably setup differently 😄 
The error I get is because we're deleting some files (the `requitements`) that are expected.
I should be able to change this behaviour quite easily, but I'm juggling through a lot of things so this might require me a bit of time. I apologise! I'll get back here as soon as I can!

2024-04-22 12:30 UTC, claudiofantacci commented
Ok, I've prepared internal changes that we're testing to get this PR through 🚀 

In the meantime, can you please update `README.md` according to the changes of this PR?

2024-04-22 16:20 UTC, claudiofantacci commented
Ok the PR is in, can you rebase and update the `README.md`? 😄

2024-04-22 17:56 UTC, claudiofantacci reviewed
Ok the #98 is in, can you rebase and update the `README.md`?

2024-04-22 17:57 UTC, claudiofantacci requested changes
Ok the #98 is in, can you rebase and update the `README.md`?

2024-04-23 09:07 UTC, SauravMaheshkar commented
Sorry for the delay, I updated the `README` in [2a2d526](https://github.com/google-deepmind/dm_pix/pull/97/commits/2a2d52689593bd934db30ad5137242cc58f0cb5c)

2024-04-23 09:10 UTC, claudiofantacci requested changes

2024-04-23 09:16 UTC, claudiofantacci approved these changes
Amazing, thanks!

2024-04-23 13:17 UTC, merged